/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.example.GUI;

import org.example.BUS.SinhVienBUS;
import org.example.DTO.SinhVien;
import org.example.DTO.ThongKe;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 *
 * @author User
 */
public class SinhVienForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SinhVienForm.class.getName());
    private List<String> selectedNganhHoc = new ArrayList<>();
    private static SinhVien selectedSinhVien = null;
    private final SinhVienBUS sinhVienBUS = new SinhVienBUS();
    /**
     * Creates new form SinhVienFrom
     */
    public SinhVienForm() {
        initComponents();
        var dssv = sinhVienBUS.getDanhSachSinhVien();
        initTable(dssv);
        ThongKe thongKe = sinhVienBUS.thongKeSinhVien(dssv);
        lblTongNam.setText(String.valueOf(thongKe.getTongNam()));
        lblTongNu.setText(String.valueOf(thongKe.getTongNu()));
        for(Component comp : popupNganhHoc.getComponents()) {
            if(comp instanceof JCheckBoxMenuItem) {
                JCheckBoxMenuItem item = (JCheckBoxMenuItem) comp;
                item.addMouseListener(new MouseAdapter() {
                    @Override
                    public void mousePressed(MouseEvent e) {
                        if(SwingUtilities.isLeftMouseButton(e)) {
                            if(!item.isSelected()){
                                selectedNganhHoc.add(item.getText());

                            } else {
                                selectedNganhHoc.remove(item.getText());
                            }
                            e.consume();
                            System.out.println(selectedNganhHoc.size());
                        }
                    }
                });
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        popupNganhHoc = new javax.swing.JPopupMenu();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem3 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem4 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtMaSv = new javax.swing.JTextField();
        txtHoTen = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        radNu = new javax.swing.JRadioButton();
        radNam = new javax.swing.JRadioButton();
        cboNganhHoc = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dateNgaySinh = new com.toedter.calendar.JDateChooser();
        btnThem = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton5 = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        chkBongDa = new javax.swing.JCheckBox();
        ckbBongBan = new javax.swing.JCheckBox();
        ckbBongRo = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblTongNam = new javax.swing.JLabel();
        lblTongNu = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSinhVien = new javax.swing.JTable();

        jCheckBoxMenuItem2.setText("CNTT");
        jCheckBoxMenuItem2.setToolTipText("");
        popupNganhHoc.add(jCheckBoxMenuItem2);

        jCheckBoxMenuItem3.setText("Kinh tế");
        popupNganhHoc.add(jCheckBoxMenuItem3);

        jCheckBoxMenuItem4.setText("Ngôn ngữ anh");
        popupNganhHoc.add(jCheckBoxMenuItem4);

        jCheckBoxMenuItem1.setText("Luật");
        popupNganhHoc.add(jCheckBoxMenuItem1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Mã SV:");

        jLabel2.setText("Họ tên:");

        jLabel3.setText("Giới tính");

        buttonGroup1.add(radNu);
        radNu.setText("Nữ");

        buttonGroup1.add(radNam);
        radNam.setSelected(true);
        radNam.setText("Nam");

        cboNganhHoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CNTT", "Kinh tế", "Ngôn ngữ anh", "Luật" }));

        jLabel4.setText("Ngành:");

        jLabel5.setText("Ngày sinh");

        btnThem.setText("Thêm");
        btnThem.addActionListener(this::btnThemActionPerformed);

        btnLamMoi.setText("Làm mới");
        btnLamMoi.addActionListener(this::btnLamMoiActionPerformed);

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(this::btnXoaActionPerformed);

        btnSua.setText("Sửa");
        btnSua.addActionListener(this::btnSuaActionPerformed);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Tìm kiếm");

        jLabel7.setText("Tên SV");

        jButton5.setText("Chọn ngành học");
        jButton5.addActionListener(this::jButton5ActionPerformed);

        btnSearch.setText("Tìm kiếm");
        btnSearch.addActionListener(this::btnSearchActionPerformed);

        chkBongDa.setText("Bóng đá");

        ckbBongBan.setText("Bóng bàn");

        ckbBongRo.setText("Bóng rổ");

        jLabel8.setText("Thể thao");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Thống kê");

        jLabel10.setText("Số nam:");

        lblTongNam.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTongNam.setText("0");

        lblTongNu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTongNu.setText("0");

        jLabel13.setText("Số nữ:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 965, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMaSv, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dateNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnThem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnXoa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSua)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLamMoi))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(radNam)
                        .addGap(18, 18, 18)
                        .addComponent(radNu)
                        .addGap(49, 49, 49)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(cboNganhHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ckbBongBan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ckbBongRo)
                                .addGap(18, 18, 18)
                                .addComponent(chkBongDa))
                            .addComponent(jLabel8)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jButton5)
                                .addGap(33, 33, 33)
                                .addComponent(btnSearch)))
                        .addGap(74, 74, 74)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblTongNam)
                                .addGap(33, 33, 33)
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(lblTongNu))
                            .addComponent(jLabel9))))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtMaSv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addComponent(dateNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(radNam)
                            .addComponent(radNu)
                            .addComponent(cboNganhHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkBongDa)
                            .addComponent(ckbBongRo)
                            .addComponent(ckbBongBan))
                        .addGap(43, 43, 43)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnXoa)
                    .addComponent(btnSua)
                    .addComponent(btnLamMoi))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jButton5)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch)
                    .addComponent(jLabel10)
                    .addComponent(lblTongNam)
                    .addComponent(lblTongNu)
                    .addComponent(jLabel13))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        tblSinhVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã SV", "Họ Tên", "Giới tính", "Ngày sinh", "Ngành", "Thể thao"
            }
        ));
        tblSinhVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSinhVienMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblSinhVien);

        getContentPane().add(jScrollPane2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void initTable(List<SinhVien> dssv) {
        DefaultTableModel model = (DefaultTableModel)  tblSinhVien.getModel();
        model.setRowCount(0);
        for(var sv : dssv) {
            Object[] row = new Object[] {
                    sv.getMaSV(),
                    sv.getHoTen(),
                    sv.getGioiTinh() == 1 ? "Nam" : "Nữ",
                    new SimpleDateFormat("dd/MM/yyyy").format(sv.getNgaySinh()),
                    sv.getNganhHoc(),
                    sv.getKyNang()
            };
            model.addRow(row);
        }

    }

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        txtMaSv.setText("");
        txtHoTen.setText("");
        dateNgaySinh.setDate(new Date());
        radNam.setSelected(true);
        cboNganhHoc.setSelectedIndex(0);
        txtMaSv.setEnabled(true);
        chkBongDa.setSelected(false);
        ckbBongBan.setSelected(false);
        ckbBongRo.setSelected(false);
        selectedSinhVien = null;
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       popupNganhHoc.show(jButton5, 0, jButton5.getHeight());
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        try{
            SinhVien sv = new SinhVien();
            sv.setMaSV(txtMaSv.getText());
            sv.setHoTen(txtHoTen.getText());
            sv.setGioiTinh(radNam.isSelected() ? 1 : 0); // Nam: 1, Nữ: 0
            sv.setNganhHoc(cboNganhHoc.getSelectedItem().toString());
            sv.setNgaySinh(dateNgaySinh.getDate());
            List<String> kyNang = new ArrayList<>();
            if(ckbBongRo.isSelected()) {
                kyNang.add("Bóng rổ");
            }
            if(ckbBongBan.isSelected())
                kyNang.add("Bóng bàn");
            if(chkBongDa.isSelected())
                kyNang.add("Bóng đá");
            sv.setKyNang(String.join(",", kyNang));
            sinhVienBUS.addSinhVien(sv);
            initTable(sinhVienBUS.getDanhSachSinhVien());
            this.btnLamMoi.doClick();
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int rowSelected= tblSinhVien.getSelectedRow();
        if(rowSelected == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn sinh viên để xóa", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int choose = JOptionPane.showConfirmDialog(this,
                "Bạn có chắc chắn muốn xóa sinh viên này không?",
                "Xác nhận xóa",
                JOptionPane.YES_NO_OPTION);
        if(choose != JOptionPane.YES_OPTION) {
            return;
        }
        String masv = tblSinhVien.getValueAt(rowSelected, 0).toString();
        sinhVienBUS.deleteSinhVien(masv);
        initTable(sinhVienBUS.getDanhSachSinhVien());
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        int rowSelected = tblSinhVien.getSelectedRow();
        if(rowSelected == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn sinh viên để cập nhật", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try{
            String id = tblSinhVien.getValueAt(rowSelected, 0).toString();
            SinhVien sv = new SinhVien();
            sv.setMaSV(id);
            sv.setGioiTinh(radNam.isSelected() ? 1 : 0);
            sv.setHoTen(txtHoTen.getText());
            String ngangHoc = cboNganhHoc.getSelectedItem().toString();
            sv.setNganhHoc(ngangHoc);
            sv.setNgaySinh(dateNgaySinh.getDate());
            List<String> kyNang = new ArrayList<>();
            if(ckbBongRo.isSelected()) {
                kyNang.add("Bóng rổ");
            }
            if(ckbBongBan.isSelected())
                kyNang.add("Bóng bàn");
            if(chkBongDa.isSelected())
                kyNang.add("Bóng đá");
            sv.setKyNang(String.join(",", kyNang));
            sinhVienBUS.updateSinhVien(sv);
            initTable(sinhVienBUS.getDanhSachSinhVien());
            this.btnLamMoi.doClick();
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void tblSinhVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSinhVienMouseClicked
        int selectedRow = tblSinhVien.getSelectedRow();
        if(selectedRow != -1) {
            String maSv = tblSinhVien.getValueAt(selectedRow, 0).toString();
            SinhVien sv = sinhVienBUS.getSinhVienById(maSv);
            if(sv != null) {
                selectedSinhVien = sv;
                txtMaSv.setText(sv.getMaSV());
                txtHoTen.setText(sv.getHoTen());
                dateNgaySinh.setDate(sv.getNgaySinh());
                txtMaSv.setEnabled(false);
                if(sv.getGioiTinh() == 1) {
                    radNam.setSelected(true);
                } else {
                    radNu.setSelected(true);
                }
                cboNganhHoc.setSelectedItem(sv.getNganhHoc());
                chkBongDa.setSelected(false);
                ckbBongBan.setSelected(false);
                ckbBongRo.setSelected(false);
                String[] kyNang = selectedSinhVien.getKyNang().split(",");
                for(var ky : kyNang) {
                    if (ky.trim().equals("Bóng đá")) chkBongDa.setSelected(true);
                    if (ky.trim().equals("Bóng rổ")) ckbBongRo.setSelected(true);
                    if (ky.trim().equals("Bóng bàn")) ckbBongBan.setSelected(true);
                }

            }
        }
    }//GEN-LAST:event_tblSinhVienMouseClicked

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
           var dssv = sinhVienBUS.searchSinhVien(txtSearch.getText(), selectedNganhHoc);
        ThongKe thongKe = sinhVienBUS.thongKeSinhVien(dssv);
        lblTongNam.setText(String.valueOf(thongKe.getTongNam()));
        lblTongNu.setText(String.valueOf(thongKe.getTongNu()));
            initTable(dssv);


    }//GEN-LAST:event_btnSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SinhVienForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cboNganhHoc;
    private javax.swing.JCheckBox chkBongDa;
    private javax.swing.JCheckBox ckbBongBan;
    private javax.swing.JCheckBox ckbBongRo;
    private com.toedter.calendar.JDateChooser dateNgaySinh;
    private javax.swing.JButton jButton5;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem3;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblTongNam;
    private javax.swing.JLabel lblTongNu;
    private javax.swing.JPopupMenu popupNganhHoc;
    private javax.swing.JRadioButton radNam;
    private javax.swing.JRadioButton radNu;
    private javax.swing.JTable tblSinhVien;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtMaSv;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
